INSERT INTO constraints ("constraint", locations) VALUES
    ('transparent',                                                                  'https://html.spec.whatwg.org/multipage/dom.html#transparent-content-models'),
    ('metadata-content',                                                             'https://html.spec.whatwg.org/multipage/dom.html#metadata-content'),
    ('flow-content',                                                                 'https://html.spec.whatwg.org/multipage/dom.html#flow-content'),
    ('sectioning-content',                                                           'https://html.spec.whatwg.org/multipage/dom.html#sectioning-content'),
    ('heading-content',                                                              'https://html.spec.whatwg.org/multipage/dom.html#heading-content'),
    ('phrasing-content',                                                             'https://html.spec.whatwg.org/multipage/dom.html#phrasing-content'),
    ('embedded-content',                                                             'https://html.spec.whatwg.org/multipage/dom.html#embedded-content-2'),
    ('interactive-content',                                                          'https://html.spec.whatwg.org/multipage/dom.html#interactive-content'),
    ('sectioning-roots',                                                             'https://html.spec.whatwg.org/multipage/sections.html#sectioning-root'),
    ('form-associated-elements',                                                     'https://html.spec.whatwg.org/multipage/forms.html#form-associated-element'),
    ('listed-elements',                                                              'https://html.spec.whatwg.org/multipage/forms.html#category-listed'),
    ('submittable-elements',                                                         'https://html.spec.whatwg.org/multipage/forms.html#category-submit'),
    ('resettable-elements',                                                          'https://html.spec.whatwg.org/multipage/forms.html#category-reset'),
    ('autocapitalize-inheriting-elements',                                           'https://html.spec.whatwg.org/multipage/forms.html#category-autocapitalize'),
    ('labelable-elements',                                                           'https://html.spec.whatwg.org/multipage/forms.html#category-label'),
    ('palpable-content',                                                             'https://html.spec.whatwg.org/multipage/dom.html#palpable-content'),
    ('script-supporting-elements',                                                   'https://html.spec.whatwg.org/multipage/dom.html#script-supporting-elements'),
    ('text',                                                                         'https://html.spec.whatwg.org/multipage/dom.html#text-content'),

    ('has-src-attribute',                                                            'https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-embed-element'),
    ('child-of-ol',                                                                  'https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element'),
    ('child-of-video-or-audio',                                                      'https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element'),
    ('child-of-picture',                                                             'https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element'),

    ('transparent-with-a-exceptions',                                                'https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element'),
    ('flow-content-with-address-exceptions',                                         'https://html.spec.whatwg.org/multipage/sections.html#the-address-element'),
    ('source-then-track-then-transparent-with-exceptions',                           'https://html.spec.whatwg.org/multipage/media.html#the-audio-element https://html.spec.whatwg.org/multipage/media.html#the-video-element'),
    ('phrasing-content-without-interactive-content-descendants',                     'https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element'),
    ('transparent-with-canvas-exceptions',                                           'https://html.spec.whatwg.org/multipage/canvas.html#the-canvas-element'),
    ('flow-content-without-table-descendants',                                       'https://html.spec.whatwg.org/multipage/tables.html#the-caption-element'),
    ('col-and-template-having-span-attribute',                                       'https://html.spec.whatwg.org/multipage/tables.html#the-colgroup-element'),
    ('phrasing-content-or-option-and-script-supporting',                             'https://html.spec.whatwg.org/multipage/form-elements.html#the-datalist-element'),
    ('summary-then-flow-content',                                                    'https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element'),
    ('phrasing-content-without-dfn-descendants',                                     'https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-dfn-element'),
    ('dt-then-dd-and-script-supporting-otherwise-flow-content',                      'https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element'),
    ('groups-of-dt-then-dd-or-divs-and-script-supporting',                           'https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element'),
    ('flow-content-with-dt-exceptions',                                              'https://html.spec.whatwg.org/multipage/grouping-content.html#the-dt-element'),
    ('legend-followed-by-flow-content',                                              'https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element'),
    ('optional-figcaption-before-or-after-flow-content',                             'https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element'),
    ('flow-content-without-header-or-footer-descendants',                            'https://html.spec.whatwg.org/multipage/sections.html#the-footer-element https://html.spec.whatwg.org/multipage/sections.html#the-header-element'),
    ('flow-content-without-form-descendants',                                        'https://html.spec.whatwg.org/multipage/forms.html#the-form-element'),
    ('metadata-content-with-head-exceptions',                                        'https://html.spec.whatwg.org/multipage/semantics.html#the-head-element'),
    ('headings-and-script-supporting',                                               'https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element'),
    ('head-then-body',                                                               'https://html.spec.whatwg.org/multipage/semantics.html#the-html-element'),
    ('phrasing-content-with-single-labelable-descendant',                            'https://html.spec.whatwg.org/multipage/forms.html#the-label-element'),
    ('phrasing-and-heading-content',                                                 'https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element https://html.spec.whatwg.org/multipage/interactive-elements.html#the-summary-element'),
    ('li-and-script-supporting',                                                     'https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element https://html.spec.whatwg.org/multipage/grouping-content.html#the-ol-element https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element'),
    ('phrasing-content-without-meter-descendants',                                   'https://html.spec.whatwg.org/multipage/form-elements.html#the-meter-element'),
    ('scripting-dependant-constraints',                                              'https://html.spec.whatwg.org/multipage/scripting.html#the-noscript-element'),
    ('param-then-transparent',                                                       'https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-object-element'),
    ('option-and-script-supporting',                                                 'https://html.spec.whatwg.org/multipage/form-elements.html#the-optgroup-element'),
    ('text-with-option-exceptions',                                                  'https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element'),
    ('source-then-single-img-and-script-supporting',                                 'https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element'),
    ('phrasing-content-without-progress-descendants',                                'https://html.spec.whatwg.org/multipage/form-elements.html#the-progress-element'),
    ('ruby-constraints',                                                             'https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-ruby-element'),
    ('script-constraints',                                                           'https://html.spec.whatwg.org/multipage/scripting.html#the-script-element'),
    ('option-optgroup-and-script-supporting',                                        'https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element'),
    ('stylesheet',                                                                   'https://html.spec.whatwg.org/multipage/semantics.html#the-style-element'),
    ('table-constraints',                                                            'https://html.spec.whatwg.org/multipage/tables.html#the-table-element'),
    ('tr-and-script-supporting',                                                     'https://html.spec.whatwg.org/multipage/tables.html#the-tbody-element https://html.spec.whatwg.org/multipage/tables.html#the-tfoot-element https://html.spec.whatwg.org/multipage/tables.html#the-thead-element'),
    ('flow-content-without-header-footer-sectioning-or-heading-content-descendants', 'https://html.spec.whatwg.org/multipage/tables.html#the-th-element'),
    ('phrasing-content-having-datetime-attribute-otherwise-text',                    'https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-time-element'),
    ('text-without-ie-whitespace',                                                   'https://html.spec.whatwg.org/multipage/semantics.html#the-title-element'),
    ('td-th-and-script-supporting',                                                  'https://html.spec.whatwg.org/multipage/tables.html#the-tr-element'),

    ('is-descendant-of-map',                                                         'https://html.spec.whatwg.org/multipage/dom.html#flow-content-2'),
    ('is-allowed-in-body',                                                           'https://html.spec.whatwg.org/multipage/dom.html#flow-content-2'),
    ('is-hierarchically-correct-main',                                               'https://html.spec.whatwg.org/multipage/grouping-content.html#hierarchically-correct-main-element'),
    ('has-itemprop-attribute',                                                       'https://html.spec.whatwg.org/multipage/dom.html#flow-content-2'),
    ('has-href-attribute',                                                           'https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2'),
    ('has-controls-attribute',                                                       'https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2 https://html.spec.whatwg.org/multipage/dom.html#palpable-content'),
    ('has-usemap-attribute',                                                         'https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2'),
    ('type-attribute-not-hidden',                                                    'https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2 https://html.spec.whatwg.org/multipage/forms.html#category-label https://html.spec.whatwg.org/multipage/dom.html#palpable-content'),
    ('has-name-value-child',                                                         'https://html.spec.whatwg.org/multipage/dom.html#palpable-content'),
    ('has-li-child',                                                                 'https://html.spec.whatwg.org/multipage/dom.html#palpable-content')

ON CONFLICT DO NOTHING;
