INSERT INTO constraints ("constraint", locations) VALUES
    ('transparent',                             'https://html.spec.whatwg.org/multipage/dom.html#transparent-content-models', ''),
    ('metadata-content',                        'https://html.spec.whatwg.org/multipage/dom.html#metadata-content'),
    ('flow-content',                            'https://html.spec.whatwg.org/multipage/dom.html#flow-content'),
    ('sectioning-content',                      'https://html.spec.whatwg.org/multipage/dom.html#sectioning-content'),
    ('heading-content',                         'https://html.spec.whatwg.org/multipage/dom.html#heading-content'),
    ('phrasing-content',                        'https://html.spec.whatwg.org/multipage/dom.html#phrasing-content'),
    ('embedded-content',                        'https://html.spec.whatwg.org/multipage/dom.html#embedded-content-2'),
    ('interactive-content',                     'https://html.spec.whatwg.org/multipage/dom.html#interactive-content'),
    ('sectioning-roots',                        'https://html.spec.whatwg.org/multipage/sections.html#sectioning-root'),
    ('form-associated-elements',                'https://html.spec.whatwg.org/multipage/forms.html#form-associated-element'),
    ('listed-elements',                         'https://html.spec.whatwg.org/multipage/forms.html#category-listed'),
    ('submittable-elements',                    'https://html.spec.whatwg.org/multipage/forms.html#category-submit'),
    ('resettable-elements',                     'https://html.spec.whatwg.org/multipage/forms.html#category-reset'),
    ('autocapitalize-inheriting-elements',      'https://html.spec.whatwg.org/multipage/forms.html#category-autocapitalize'),
    ('labelable-elements',                      'https://html.spec.whatwg.org/multipage/forms.html#category-label'),
    ('palpable-content',                        'https://html.spec.whatwg.org/multipage/dom.html#palpable-content'),
    ('script-supporting-elements',              'https://html.spec.whatwg.org/multipage/dom.html#script-supporting-elements'),

    ('has-src-attribute',                                                          'https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-embed-element', ''),
    ('child-of-ol',                                                                'https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element', ''),
    ('child-of-video-or-audio',                                                    'https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element', ''),
    ('child-of-picture',                                                           'https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element', ''),
    ('no-interactive-content-a-or-tabindex-attribute-descendants',                 'https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element', ''),
    ('no-heading-content-sectioning-content-header-footer-or-address-descendants', 'https://html.spec.whatwg.org/multipage/sections.html#the-address-element', ''),
    ('no-media-element-descendants',                                               'https://html.spec.whatwg.org/multipage/media.html#the-audio-element', ''),
    ('no-interactive-content-or-tabindex-attribute-descendants',                   'https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element', ''),
    ('no-interactive-content-with-canvas-exceptions',                              'https://html.spec.whatwg.org/multipage/canvas.html#the-canvas-element', ''),
    ('no-table-descendants',                                                       'https://html.spec.whatwg.org/multipage/tables.html#the-caption-element')
ON CONFLICT DO NOTHING;
