-- Generated. See gentool.js.
module Html.Attributes where

data Attribute a = 
      Abbr a
    | Accept a
    | AcceptCharset a
    | AccessKey a
    | Action a
    | Allow a
    | AllowFullScreen a
    | Alt a
    | As a
    | Async a
    | AutoCapitalize a
    | AutoComplete a
    | AutoFocus a
    | AutoPlay a
    | Charset a
    | Checked a
    | Cite a
    | Class a
    | Color a
    | Cols a
    | Colspan a
    | Content a
    | ContentEditable a
    | Controls a
    | Coords a
    | CrossOrigin a
    | Data a
    | DateTime a
    | Decoding a
    | Default a
    | Defer a
    | Dir a
    | Dirname a
    | Disabled a
    | DownLoad a
    | Draggable a
    | Enctype a
    | EnterKeyHint a
    | For a
    | Form a
    | FormAction a
    | FormEnctype a
    | FormMethod a
    | FormNoValidate a
    | FormTarget a
    | Headers a
    | Height a
    | Hidden a
    | High a
    | Href a
    | HrefLang a
    | HttpEquiv a
    | Id a
    | ImageSizes a
    | ImageSrcSet a
    | InputMode a
    | Integrity a
    | Is a
    | IsMap a
    | ItemId a
    | ItemProp a
    | ItemRef a
    | ItemScope a
    | ItemType a
    | Kind a
    | Label a
    | Lang a
    | List a
    | Loading a
    | Loop a
    | Low a
    | Max a
    | MaxLength a
    | Media a
    | Method a
    | Min a
    | MinLength a
    | Multiple a
    | Muted a
    | Name a
    | NoModule a
    | Nonce a
    | NoValidate a
    | OnAbort a
    | OnAfterPrint a
    | OnAuxClick a
    | OnBeforePrint a
    | OnBeforeUnload a
    | OnBlur a
    | OnCancel a
    | OnCanPlay a
    | OnCanPlayThrough a
    | OnChange a
    | OnClick a
    | OnClose a
    | OnContextMenu a
    | OnCopy a
    | OnCueChange a
    | OnCut a
    | OnDblClick a
    | OnDrag a
    | OnDragEnd a
    | OnDragEnter a
    | OnDragLeave a
    | OnDragOver a
    | OnDragStart a
    | OnDrop a
    | OnDurationChange a
    | OnEmptied a
    | OnEnded a
    | OnError a
    | OnFocus a
    | OnFormData a
    | OnHashChange a
    | OnInput a
    | OnInvalid a
    | OnKeyDown a
    | OnKeyPress a
    | OnKeyup a
    | OnLanguageChange a
    | OnLoad a
    | OnLoadedData a
    | OnLoadedMetaData a
    | OnLoadStart a
    | OnMessage a
    | OnMessageError a
    | OnMouseDown a
    | OnMouseEnter a
    | OnMouseLeave a
    | OnMouseMove a
    | OnMouseOut a
    | OnMouseOver a
    | OnMouseUp a
    | OnOffline a
    | OnOnline a
    | OnPageHide a
    | OnPageShow a
    | OnPaste a
    | OnPause a
    | OnPlay a
    | OnPlaying a
    | OnPopState a
    | OnProgress a
    | OnRateChange a
    | OnRejectionHandled a
    | OnReset a
    | OnResize a
    | OnScroll a
    | OnSecurityPolicyViolation a
    | OnSeeked a
    | OnSeeking a
    | OnSelect a
    | OnSlotChange a
    | OnStalled a
    | OnStorage a
    | OnSubmit a
    | OnSuspend a
    | OnTimeUpdate a
    | OnToggle a
    | OnUnhandledRejection a
    | OnUnload a
    | OnVolumeChange a
    | OnWaiting a
    | OnWheel a
    | Open a
    | Optimum a
    | Pattern a
    | Ping a
    | Placeholder a
    | PlaysInline a
    | Poster a
    | Preload a
    | Readonly a
    | ReferrerPolicy a
    | Rel a
    | Required a
    | Reversed a
    | Rows a
    | Rowspan a
    | Sandbox a
    | Scope a
    | Selected a
    | Shape a
    | Size a
    | Sizes a
    | Slot a
    | Span a
    | SpellCheck a
    | Src a
    | Srcdoc a
    | SrcLang a
    | SrcSet a
    | Start a
    | Step a
    | Style a
    | TabIndex a
    | Target a
    | Title a
    | Translate a
    | Type a
    | UseMap a
    | Value a
    | Width a
    | Wrap a
    deriving (Show)

abbr, accept, acceptCharset, accessKey, action, allow, allowFullScreen, alt, as, async, autoCapitalize, autoComplete, autoFocus, autoPlay, charset, checked, cite, class_, color, cols, colspan, content, contentEditable, controls, coords, crossOrigin, data_, dateTime, decoding, default_, defer, dir, dirname, disabled, downLoad, draggable, enctype, enterKeyHint, for, form, formAction, formEnctype, formMethod, formNoValidate, formTarget, headers, height, hidden, high, href, hrefLang, httpEquiv, id, imageSizes, imageSrcSet, inputMode, integrity, is, isMap, itemId, itemProp, itemRef, itemScope, itemType, kind, label, lang, list, loading, loop, low, max, maxLength, media, method, min, minLength, multiple, muted, name, noModule, nonce, noValidate, onAbort, onAfterPrint, onAuxClick, onBeforePrint, onBeforeUnload, onBlur, onCancel, onCanPlay, onCanPlayThrough, onChange, onClick, onClose, onContextMenu, onCopy, onCueChange, onCut, onDblClick, onDrag, onDragEnd, onDragEnter, onDragLeave, onDragOver, onDragStart, onDrop, onDurationChange, onEmptied, onEnded, onError, onFocus, onFormData, onHashChange, onInput, onInvalid, onKeyDown, onKeyPress, onKeyup, onLanguageChange, onLoad, onLoadedData, onLoadedMetaData, onLoadStart, onMessage, onMessageError, onMouseDown, onMouseEnter, onMouseLeave, onMouseMove, onMouseOut, onMouseOver, onMouseUp, onOffline, onOnline, onPageHide, onPageShow, onPaste, onPause, onPlay, onPlaying, onPopState, onProgress, onRateChange, onRejectionHandled, onReset, onResize, onScroll, onSecurityPolicyViolation, onSeeked, onSeeking, onSelect, onSlotChange, onStalled, onStorage, onSubmit, onSuspend, onTimeUpdate, onToggle, onUnhandledRejection, onUnload, onVolumeChange, onWaiting, onWheel, open, optimum, pattern_, ping, placeholder, playsInline, poster, preload, readonly, referrerPolicy, rel, required, reversed, rows, rowspan, sandbox, scope, selected, shape, size, sizes, slot, span, spellCheck, src, srcdoc, srcLang, srcSet, start, step, style, tabIndex, target, title, translate, type_, useMap, value, width, wrap :: a -> Attribute a
abbr = Abbr
accept = Accept
acceptCharset = AcceptCharset
accessKey = AccessKey
action = Action
allow = Allow
allowFullScreen = AllowFullScreen
alt = Alt
as = As
async = Async
autoCapitalize = AutoCapitalize
autoComplete = AutoComplete
autoFocus = AutoFocus
autoPlay = AutoPlay
charset = Charset
checked = Checked
cite = Cite
class_ = Class
color = Color
cols = Cols
colspan = Colspan
content = Content
contentEditable = ContentEditable
controls = Controls
coords = Coords
crossOrigin = CrossOrigin
data_ = Data
dateTime = DateTime
decoding = Decoding
default_ = Default
defer = Defer
dir = Dir
dirname = Dirname
disabled = Disabled
downLoad = DownLoad
draggable = Draggable
enctype = Enctype
enterKeyHint = EnterKeyHint
for = For
form = Form
formAction = FormAction
formEnctype = FormEnctype
formMethod = FormMethod
formNoValidate = FormNoValidate
formTarget = FormTarget
headers = Headers
height = Height
hidden = Hidden
high = High
href = Href
hrefLang = HrefLang
httpEquiv = HttpEquiv
id = Id
imageSizes = ImageSizes
imageSrcSet = ImageSrcSet
inputMode = InputMode
integrity = Integrity
is = Is
isMap = IsMap
itemId = ItemId
itemProp = ItemProp
itemRef = ItemRef
itemScope = ItemScope
itemType = ItemType
kind = Kind
label = Label
lang = Lang
list = List
loading = Loading
loop = Loop
low = Low
max = Max
maxLength = MaxLength
media = Media
method = Method
min = Min
minLength = MinLength
multiple = Multiple
muted = Muted
name = Name
noModule = NoModule
nonce = Nonce
noValidate = NoValidate
onAbort = OnAbort
onAfterPrint = OnAfterPrint
onAuxClick = OnAuxClick
onBeforePrint = OnBeforePrint
onBeforeUnload = OnBeforeUnload
onBlur = OnBlur
onCancel = OnCancel
onCanPlay = OnCanPlay
onCanPlayThrough = OnCanPlayThrough
onChange = OnChange
onClick = OnClick
onClose = OnClose
onContextMenu = OnContextMenu
onCopy = OnCopy
onCueChange = OnCueChange
onCut = OnCut
onDblClick = OnDblClick
onDrag = OnDrag
onDragEnd = OnDragEnd
onDragEnter = OnDragEnter
onDragLeave = OnDragLeave
onDragOver = OnDragOver
onDragStart = OnDragStart
onDrop = OnDrop
onDurationChange = OnDurationChange
onEmptied = OnEmptied
onEnded = OnEnded
onError = OnError
onFocus = OnFocus
onFormData = OnFormData
onHashChange = OnHashChange
onInput = OnInput
onInvalid = OnInvalid
onKeyDown = OnKeyDown
onKeyPress = OnKeyPress
onKeyup = OnKeyup
onLanguageChange = OnLanguageChange
onLoad = OnLoad
onLoadedData = OnLoadedData
onLoadedMetaData = OnLoadedMetaData
onLoadStart = OnLoadStart
onMessage = OnMessage
onMessageError = OnMessageError
onMouseDown = OnMouseDown
onMouseEnter = OnMouseEnter
onMouseLeave = OnMouseLeave
onMouseMove = OnMouseMove
onMouseOut = OnMouseOut
onMouseOver = OnMouseOver
onMouseUp = OnMouseUp
onOffline = OnOffline
onOnline = OnOnline
onPageHide = OnPageHide
onPageShow = OnPageShow
onPaste = OnPaste
onPause = OnPause
onPlay = OnPlay
onPlaying = OnPlaying
onPopState = OnPopState
onProgress = OnProgress
onRateChange = OnRateChange
onRejectionHandled = OnRejectionHandled
onReset = OnReset
onResize = OnResize
onScroll = OnScroll
onSecurityPolicyViolation = OnSecurityPolicyViolation
onSeeked = OnSeeked
onSeeking = OnSeeking
onSelect = OnSelect
onSlotChange = OnSlotChange
onStalled = OnStalled
onStorage = OnStorage
onSubmit = OnSubmit
onSuspend = OnSuspend
onTimeUpdate = OnTimeUpdate
onToggle = OnToggle
onUnhandledRejection = OnUnhandledRejection
onUnload = OnUnload
onVolumeChange = OnVolumeChange
onWaiting = OnWaiting
onWheel = OnWheel
open = Open
optimum = Optimum
pattern_ = Pattern
ping = Ping
placeholder = Placeholder
playsInline = PlaysInline
poster = Poster
preload = Preload
readonly = Readonly
referrerPolicy = ReferrerPolicy
rel = Rel
required = Required
reversed = Reversed
rows = Rows
rowspan = Rowspan
sandbox = Sandbox
scope = Scope
selected = Selected
shape = Shape
size = Size
sizes = Sizes
slot = Slot
span = Span
spellCheck = SpellCheck
src = Src
srcdoc = Srcdoc
srcLang = SrcLang
srcSet = SrcSet
start = Start
step = Step
style = Style
tabIndex = TabIndex
target = Target
title = Title
translate = Translate
type_ = Type
useMap = UseMap
value = Value
width = Width
wrap = Wrap